### ISSUE TITLE
Tenant Deploy fails with Unable to retrieve Arn attribute for AWS::Cognito::UserPool

### ISSUE THREAD

**Issue by sathish0804** [aws-solutions-library-samples/guidance-for-aws-sustainability-insights-framework#28]
while deploying the SIF,
[SIF Deployment](https://github.com/aws-solutions-library-samples/guidance-for-aws-sustainability-insights-framework/blob/main/docs/deployment/cdk_walkthrough.md), i'm getting this error

**Running this command fails with missing permission on CongnitoUserPool**

`npm run cdk -- deploy \
 -c tenantId=<tenantId> \
 -c environment=<environment> \
 -c administratorEmail=<administratorEmail> \
 -c enableDeleteResource=true \
 -c includeCaml=true \
 -c deleteBucket=true \
 -r arn:aws:iam::<ACCOUNT ID>:role/sif-deploy-role
 --all --require-approval never --concurrency=10    
 `
**Error Details:**
The error indicates that the sif-deploy-role is not authorized to perform the cognito-idp:DescribeUserPool action on the specified Cognito User Pool.
This might be due to missing permissions in the IAM policy attached to the sif-deploy-role
**The complete error message is as follow:**

`Stack deploy failed (the stack disappeared while we were deploying it): Unable to retrieve Arn attribute for AWS::Cognito::UserPool, with error message User: arn:aws:sts::<ACCOUNT ID>:assumed-role/sif-deploy-role/AWSCloudFormation is not authorized to perform: cognito-idp:DescribeUserPool on resource: arn:aws:cognito-idp:us-east-1:<ACCOUNT ID>:userpool/us-east-1_excjjgI46 because no identity-based policy allows the cognito-idp:DescribeUserPool action (Service: CognitoIdentityProvider, Status Code: 400, Request ID: fc4aa047-561e-4154-8c36-1c4d9fe5e778), Unable to retrieve Arn attribute for AWS::Cognito::UserPool, with error message User: arn:aws:sts::<ACCOUNT ID>:assumed-role/sif-deploy-role/AWSCloudFormation is not authorized to perform: cognito-idp:DescribeUserPool on resource: arn:aws:cognito-idp:us-east-1:<ACCOUNT ID>:userpool/us-east-1_excjjgI46 because no identity-based policy allows the cognito-idp:DescribeUserPool action (Service: CognitoIdentityProvider, Status Code: 400, Request ID: 334a5872-4282-4c2d-a5bf-fe9e578ffc33)`

I have created the IAM Role using
![image](https://github.com/user-attachments/assets/63f223b5-47cd-44b1-8731-27b9f876ddea)

**Comment by johnrotach** [comment]
Apologies, we will update this in a future release. The role is missing the following permissions:
```
"cognito-idp:DescribeUserPool",
"cognito-idp:AdminGetUser",
"cognito-idp:AdminListGroupsForUser"
```

You will also need to add the following LakeFormation policy to the deploy role:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "VisualEditor0",
      "Effect": "Allow",
      "Action": "lakeformation:*",
      "Resource": "*"
    }
  ]
}
```

**Comment by sathish0804** [comment]
now i'm getting this error,
` ❌ Deployment failed: Error [ValidationError]: Unable to fetch parameters [/sif/shared/dev/caml/inferenceEndpointName] from parameter store for this account.
    at Request.extractError (/Users/satishvanga/Desktop/data-fabric/guidance-for-aws-sustainability-insights-framework-main/common/temp/node_modules/.pnpm/aws-cdk@2.87.0/node_modules/aws-cdk/lib/index.js:307:46430)
    at Request.callListeners (/Users/satishvanga/Desktop/data-fabric/guidance-for-aws-sustainability-insights-framework-main/common/temp/node_modules/.pnpm/aws-cdk@2.87.0/node_modules/aws-cdk/lib/index.js:307:89761)
    at Request.emit (/Users/satishvanga/Desktop/data-fabric/guidance-for-aws-sustainability-insights-framework-main/common/temp/node_modules/.pnpm/aws-cdk@2.87.0/node_modules/aws-cdk/lib/index.js:307:89209)
    at Request.emit (/Users/satishvanga/Desktop/data-fabric/guidance-for-aws-sustainability-insights-framework-main/common/temp/node_modules/.pnpm/aws-cdk@2.87.0/node_modules/aws-cdk/lib/index.js:307:195751)
    at Request.transition (/Users/satishvanga/Desktop/data-fabric/guidance-for-aws-sustainability-insights-framework-main/common/temp/node_modules/.pnpm/aws-cdk@2.87.0/node_modules/aws-cdk/lib/index.js:307:189303)
    at AcceptorStateMachine.runTo (/Users/satishvanga/Desktop/data-fabric/guidance-for-aws-sustainability-insights-framework-main/common/temp/node_modules/.pnpm/aws-cdk@2.87.0/node_modules/aws-cdk/lib/index.js:307:154175)
    at /Users/satishvanga/Desktop/data-fabric/guidance-for-aws-sustainability-insights-framework-main/common/temp/node_modules/.pnpm/aws-cdk@2.87.0/node_modules/aws-cdk/lib/index.js:307:154505
    at Request.<anonymous> (/Users/satishvanga/Desktop/data-fabric/guidance-for-aws-sustainability-insights-framework-main/common/temp/node_modules/.pnpm/aws-cdk@2.87.0/node_modules/aws-cdk/lib/index.js:307:189595)
    at Request.<anonymous> (/Users/satishvanga/Desktop/data-fabric/guidance-for-aws-sustainability-insights-framework-main/common/temp/node_modules/.pnpm/aws-cdk@2.87.0/node_modules/aws-cdk/lib/index.js:307:195826)
    at Request.callListeners (/Users/satishvanga/Desktop/data-fabric/guidance-for-aws-sustainability-insights-framework-main/common/temp/node_modules/.pnpm/aws-cdk@2.87.0/node_modules/aws-cdk/lib/index.js:307:89929) {
  code: 'ValidationError',
  time: 2024-10-03T21:52:18.951Z,
  requestId: '4dbb41dd-64c7-44b6-82e1-c628f0b982d3',
  statusCode: 400,
  retryable: false,
  retryDelay: 613.7536247815742
}`

`Unable to fetch parameters [/sif/shared/dev/caml/inferenceEndpointName] from parameter store for this account.`

**Comment by johnrotach** [comment]
Hello. I see above that you deployed the tenant stack with the `includeCaml=true` context variable. Can you verify you also set this variable when deploying the platform stack? This is where the CaML endpoint is created.

**Comment by sathish0804** [comment]
sorry, I didn't, can I deploy with it again (`includeCaml=true`)
![image](https://github.com/user-attachments/assets/0218b4f4-8d06-49b4-b5b0-9dc16a5ffe1e)
but, here you are saying like `Note: This only needs to be run once per environment.`

**Comment by johnrotach** [comment]
Hello. Sorry for the confusion. CaML is a feature of SIF for using ML to match products to their EIO (economic input-output) category for Scope 3 emissions calculations. The CaML feature is used by SDF when SDF is deployed (see [demo here](https://github.com/aws-solutions-library-samples/guidance-for-building-a-sustainability-data-fabric-on-aws/tree/main/typescript/packages/demo)).

This feature in SDF supports a demo of CaML. If you do not plan to demonstrate or use this feature you can skip deploying SDF.

The CaML SageMaker endpoint is a shared resource that is deployed when the SIF platform stack is created. You can re-deploy the SIF platform stack and include the CaML flag, repeat the tenant SIF deployment with the CaML flag, and then deploy SDF to use that feature. You do not need to tear down any of the stacks - just re-deploy the CDK.

**Comment by sathish0804** [comment]
while trying to re-deploy without deleting the existing stack, it is give this 
**No stacks match the name(s)**
`npm run cdk -- deploy \
    -c environment=dev \
    -c deleteBucket=true \
    -c clusterDeletionProtection=false \
    -c includeCaml=true \    
    -r arn:aws:iam::<account_id>:role/sif-deploy-role
    --all    
`
